from typing import Protocol


class StackBase(Protocol):
    def push(self, item: int) -> None: ...

    def pop(self) -> int: ...

    def peek(self) -> int: ...

    def is_empty(self) -> bool: ...

    def __len__(self) -> int: ...

    def min(self) -> int: ...
