from typing import Protocol


class QueueBase(Protocol):
    def enqueue(self, item: int) -> None: ...

    def dequeue(self) -> int: ...

    def front(self) -> int: ...

    def is_empty(self) -> bool: ...

    def __len__(self) -> int: ...
